// <auto-generated />
using System;
using CreoHp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreoHp.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190909205357_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CreoHp.Models.Phrases.Phrase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid?>("ModifiedByUserId");

                    b.Property<string>("Text")
                        .IsUnicode(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Phrases");
                });

            modelBuilder.Entity("CreoHp.Models.Tags.PhraseTag", b =>
                {
                    b.Property<Guid>("PhraseId");

                    b.Property<Guid>("TagId");

                    b.HasKey("PhraseId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PhraseTags");
                });

            modelBuilder.Entity("CreoHp.Models.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid?>("ModifiedByUserId");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .IsUnicode(true);

                    b.Property<int>("Position");

                    b.Property<int>("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("Name", "Type")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab3a769a-e800-4e48-97b5-a577baf5ac86"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 589, DateTimeKind.Utc).AddTicks(9215),
                            IsDeleted = false,
                            Name = "Neutral",
                            Position = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 589, DateTimeKind.Utc).AddTicks(9215)
                        },
                        new
                        {
                            Id = new Guid("c1f30ee9-ec04-448c-a5cc-3fe22c64e52a"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1168),
                            IsDeleted = false,
                            Name = "Positive",
                            Position = 1,
                            Type = 0,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1168)
                        },
                        new
                        {
                            Id = new Guid("a21869d5-c093-48cb-9ce0-c80d2e08d5bd"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1193),
                            IsDeleted = false,
                            Name = "Negative",
                            Position = 2,
                            Type = 0,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1193)
                        },
                        new
                        {
                            Id = new Guid("cca290de-81f5-482d-b27c-c5aea33b0886"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1212),
                            IsDeleted = false,
                            Name = "Common",
                            Position = 0,
                            Type = 1,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1212)
                        },
                        new
                        {
                            Id = new Guid("454fc2a6-7c0b-4a89-840c-d9378da0c77d"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1219),
                            IsDeleted = false,
                            Name = "Сareer",
                            Position = 1,
                            Type = 1,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1219)
                        },
                        new
                        {
                            Id = new Guid("66956a46-cfa5-4c4f-af55-718d9d97d850"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1225),
                            IsDeleted = false,
                            Name = "Love",
                            Position = 2,
                            Type = 1,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1225)
                        },
                        new
                        {
                            Id = new Guid("f07f9df2-fcb0-4027-bfc8-67438342458f"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1231),
                            IsDeleted = false,
                            Name = "Friendship",
                            Position = 3,
                            Type = 1,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1231)
                        },
                        new
                        {
                            Id = new Guid("134e8818-a5c8-49ea-b279-29fca5ff6ce9"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1236),
                            IsDeleted = false,
                            Name = "Travels",
                            Position = 4,
                            Type = 1,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1236)
                        },
                        new
                        {
                            Id = new Guid("ddac2fa4-964e-475f-b1ff-31fa9105fbd7"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1242),
                            IsDeleted = false,
                            Name = "Children",
                            Position = 5,
                            Type = 1,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1242)
                        },
                        new
                        {
                            Id = new Guid("48f1d60c-b834-415e-bae1-4b2c867ea93d"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1249),
                            IsDeleted = false,
                            Name = "Money",
                            Position = 6,
                            Type = 1,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1249)
                        },
                        new
                        {
                            Id = new Guid("778be6b6-9233-454b-9511-9afef5dd9b53"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1254),
                            IsDeleted = false,
                            Name = "Info",
                            Position = 0,
                            Type = 2,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1254)
                        },
                        new
                        {
                            Id = new Guid("0bdcfdbd-2b7e-480b-98e0-93c2fc61b458"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1261),
                            IsDeleted = false,
                            Name = "Tip",
                            Position = 1,
                            Type = 2,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1261)
                        },
                        new
                        {
                            Id = new Guid("b8d72746-f8be-40f6-b905-23d9e2d46741"),
                            CreatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1267),
                            IsDeleted = false,
                            Name = "Warning",
                            Position = 2,
                            Type = 2,
                            UpdatedAt = new DateTime(2019, 9, 9, 20, 53, 57, 590, DateTimeKind.Utc).AddTicks(1267)
                        });
                });

            modelBuilder.Entity("CreoHp.Models.Tags.TagRelation", b =>
                {
                    b.Property<Guid>("ChildTagId");

                    b.Property<Guid>("ParentTagId");

                    b.HasKey("ChildTagId", "ParentTagId");

                    b.HasIndex("ParentTagId");

                    b.ToTable("TagRelations");
                });

            modelBuilder.Entity("CreoHp.Models.Users.AppIdentityRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("CreoHp.Models.Users.AppIdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .IsUnicode(true);

                    b.Property<int?>("Gender");

                    b.Property<bool>("IsBlocked");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .IsUnicode(true);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CreoHp.Models.Users.AppIdentityUserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CreoHp.Models.Phrases.Phrase", b =>
                {
                    b.HasOne("CreoHp.Models.Users.AppIdentityUser", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CreoHp.Models.Tags.PhraseTag", b =>
                {
                    b.HasOne("CreoHp.Models.Phrases.Phrase", "Phrase")
                        .WithMany("Tags")
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CreoHp.Models.Tags.Tag", "Tag")
                        .WithMany("Phrases")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CreoHp.Models.Tags.Tag", b =>
                {
                    b.HasOne("CreoHp.Models.Users.AppIdentityUser", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CreoHp.Models.Tags.TagRelation", b =>
                {
                    b.HasOne("CreoHp.Models.Tags.Tag", "Child")
                        .WithMany("Parents")
                        .HasForeignKey("ChildTagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CreoHp.Models.Tags.Tag", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CreoHp.Models.Users.AppIdentityUserRole", b =>
                {
                    b.HasOne("CreoHp.Models.Users.AppIdentityRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CreoHp.Models.Users.AppIdentityUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CreoHp.Models.Users.AppIdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CreoHp.Models.Users.AppIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CreoHp.Models.Users.AppIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CreoHp.Models.Users.AppIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
